import React from "react";
import PropTypes from "prop-types";
import { generateStyle } from "../../utils/helper";

const QInputBox = ({
   text,
  style,
  maxLines,
  textDirection,
  textAlign,
  overflow,
  fontSize,
  fontWeight,
  alignment,
  decoration,
  fontFamily,
  fontStyle,
  isAnimationplayed,
  width,
  height,
  padding,
  paddingLeft,
  paddingTop,
  paddingRight,
  paddingBottom,
  margin,
  marginLeft,
  marginTop,
  marginRight,
  marginBottom,
  color,
  bgColor,
  borderRadius,
  borderColor,
  borderWidth,
  bgUrl,
  isImageFill,
  shadowBlurRadius,
  shadowColor,
  shadowOffsetX,
  shadowOffsetY,
  shadowSpreadRadius,
  positionedLeft,
  positionedTop,
  positionedRight,
  positionedBottom,
  widthType,
  heightType,

  // New props added here
  isAbsoluteValue,
  borderTLR,
  borderTRR,
  borderBLR,
  borderBRR,
  borderTW,
  borderBW,
  borderLW,
  borderRW,
  borderTC,
  borderBC,
  borderLC,
  borderRC,
  mainAlignment,
  crossAlignment,
  onClick,
  zIndex,
  imageFit,
}) => {
  const inputStyle = {
  
      ...generateStyle({
                width,
                height,
                isAbsoluteValue,
                positionedLeft,
                positionedTop,
                positionedRight,
                positionedBottom,
                bgColor,
                bgUrl,
                isImageFill,
                color,
                borderRadius,
                borderTLR,
                borderTRR,
                borderBLR,
                borderBRR,
                borderWidth,
                borderColor,
                borderTW,
                borderBW,
                borderLW,
                borderRW,
                borderTC,
                borderBC,
                borderLC,
                borderRC,
                paddingLeft,
                paddingRight,
                paddingTop,
                paddingBottom,
                marginLeft,
                marginRight,
                marginTop,
                marginBottom,
                shadowOffsetX,
                shadowOffsetY,
                shadowBlurRadius,
                shadowSpreadRadius,
                shadowColor,
                overflow,
                mainAlignment,
                crossAlignment,
                onClick,
                zIndex,
                fontSize,
                fontWeight,
                textAlign,
                fontFamily,
                fontStyle,
                imageFit,
                decoration,
                textDirection

              }),

  };

  return (
    <input
      type="text"
      defaultValue={text}
      style={inputStyle}
      maxLength={maxLines ? maxLines * 100 : undefined} // Approximation for multiline
     
    />
  );
};

QInputBox.propTypes = {
  text: PropTypes.string,
  style: PropTypes.object,
  maxLines: PropTypes.number,
  textDirection: PropTypes.oneOf(["ltr", "rtl", "auto"]),
  textAlign: PropTypes.oneOf(["left", "center", "right", "justify", "start", "end"]),
  overflow: PropTypes.oneOf(["visible", "hidden", "scroll", "auto", "clip", "ellipsis"]),
  fontSize: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  fontWeight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  alignment: PropTypes.string,
  decoration: PropTypes.oneOf(["none", "underline", "line-through", "overline"]),
  fontFamily: PropTypes.string,
  fontStyle: PropTypes.oneOf(["normal", "italic", "oblique"]),
  isAnimationplayed: PropTypes.bool,
  width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  height: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  padding: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  paddingLeft: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  paddingTop: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  paddingRight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  paddingBottom: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  margin: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  marginLeft: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  marginTop: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  marginRight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  marginBottom: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  color: PropTypes.string,
  bgColor: PropTypes.string,
  borderRadius: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  borderColor: PropTypes.string,
  borderWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  bgUrl: PropTypes.string,
  isImageFill: PropTypes.bool,
  shadowBlurRadius: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  shadowColor: PropTypes.string,
  shadowOffsetX: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  shadowOffsetY: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  shadowSpreadRadius: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  positionedLeft: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  positionedTop: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  positionedRight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  positionedBottom: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  widthType: PropTypes.oneOf(["auto", "fixed"]),
  heightType: PropTypes.oneOf(["auto", "fixed"]),
};

export default QInputBox;
QInputBox.displayName = 'QInputBox';
